### ISSUE TITLE
SKSE Example Plugin TODO

### ISSUE THREAD

**Issue by xanderdunn** [xanderdunn/skaar#21]
- [x] Remove the skse directory for places to link so that the user must use "skse/File.h" imports
- [x] Include instructions to set the output directory so that the user can set it to output to the Skyrim data directory
- [x] Rename the output directory of the common project to use standard directory name
- [x] Get RELEASE build to work
- [ ] Fix vc9 not found error
- [ ] Fix SAFESH error
